"""initial schema: the 8 tables of the solo scope ⟵ DOC-016 §5

Revision ID: be4c10d62d99
Revises: 
Create Date: 2026-08-19 07:16:59.089236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4c10d62d99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_code', sa.Text(), nullable=False),
    sa.Column('subject_topic', sa.Text(), nullable=False),
    sa.Column('subject_region', sa.Text(), nullable=False),
    sa.Column('subject_language', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed', sa.Boolean(), nullable=False),
    sa.Column('not_computed_reason', sa.Text(), nullable=True),
    sa.Column('raw_value', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('baseline_mean', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('baseline_stddev', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('z_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('threshold_applied', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('n_current', sa.Integer(), nullable=False),
    sa.Column('n_sources', sa.Integer(), nullable=False),
    sa.Column('evidence_content_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_evaluated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("not_computed_reason IS NULL OR not_computed_reason IN ('below_n_min','insufficient_baseline','no_data','gate_not_met')", name='ck_score_reason_values'),
    sa.CheckConstraint("severity IS NULL OR severity IN ('normal','informational','low','medium','high','critical')", name='ck_score_severity'),
    sa.CheckConstraint('computed = true OR not_computed_reason IS NOT NULL', name='ck_score_reason'),
    sa.CheckConstraint('jsonb_array_length(evidence_content_ids) <= 50', name='ck_score_evidence_cap'),
    sa.CheckConstraint('window_end > window_start', name='ck_score_window'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code', 'subject_topic', 'subject_region', 'subject_language', 'window_end', name='ux_score_window')
    )
    op.create_index('ix_scores_pending_alert', 'indicator_scores', ['created_at'], unique=False, postgresql_where="computed AND NOT alert_evaluated AND severity IN ('low','medium','high','critical')")
    op.create_index('ix_scores_trend', 'indicator_scores', ['subject_topic', 'subject_region', 'subject_language', 'indicator_code', 'window_end'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('poll_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('health_status', sa.Text(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reliability_band', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_cursor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health_status IN ('healthy','degraded','unhealthy','config_error')", name='ck_sources_health'),
    sa.CheckConstraint("language ~ '^[a-z]{2}$'", name='ck_sources_language'),
    sa.CheckConstraint("reliability_band IN ('established','mixed','limited')", name='ck_sources_band'),
    sa.CheckConstraint("source_type IN ('rss','telegram','reddit','html_page')", name='ck_sources_type'),
    sa.CheckConstraint("status IN ('enabled','disabled')", name='ck_sources_status'),
    sa.CheckConstraint('consecutive_failures >= 0', name='ck_sources_failures'),
    sa.CheckConstraint('poll_minutes BETWEEN 5 AND 1440', name='ck_sources_poll'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_sources_due', 'sources', ['status', 'health_status', 'last_success_at'], unique=False, postgresql_where="status = 'enabled'")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email ~ '^[^@]+@[^@]+\\.[^@]+$'", name='ck_users_email_shape'),
    sa.CheckConstraint("role IN ('analyst','supervisor','admin')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active','disabled')", name='ck_users_status'),
    sa.CheckConstraint('failed_login_count >= 0', name='ck_users_failed_count'),
    sa.CheckConstraint('length(full_name) BETWEEN 1 AND 200', name='ck_users_name_len'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_code', sa.Text(), nullable=False),
    sa.Column('subject_topic', sa.Text(), nullable=False),
    sa.Column('subject_region', sa.Text(), nullable=False),
    sa.Column('subject_language', sa.Text(), nullable=False),
    sa.Column('triggering_score_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('baseline_mean', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('baseline_stddev', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('z_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('threshold_applied', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('n_items', sa.Integer(), nullable=False),
    sa.Column('n_sources', sa.Integer(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('low','medium','high','critical')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('new','acknowledged','under_review','resolved_confirmed','resolved_rejected','resolved_inconclusive')", name='ck_alerts_status'),
    sa.CheckConstraint("status NOT LIKE 'resolved%%' OR (reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)", name='ck_alerts_resolution_complete'),
    sa.CheckConstraint('occurrence_count >= 1', name='ck_alerts_occurrences'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggering_score_id'], ['indicator_scores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_queue', 'alerts', ['status', 'severity', 'created_at'], unique=False)
    op.create_index('ux_alert_open', 'alerts', ['indicator_code', 'subject_topic', 'subject_region', 'subject_language'], unique=True, postgresql_where="status IN ('new','acknowledged','under_review')")
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('user','system')", name='ck_audit_actor_type'),
    sa.CheckConstraint("result IN ('success','denied','failure')", name='ck_audit_result'),
    sa.CheckConstraint('NOT (detail::text ~* \'"(password|secret|token|api_key|password_hash)"\')', name='ck_audit_no_secrets'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_denied', 'audit_logs', ['created_at'], unique=False, postgresql_where="result = 'denied'")
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id', 'created_at'], unique=False)
    op.create_table('raw_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('length(body) > 0', name='ck_raw_body_nonempty'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_raw_effective_time', 'raw_content', [sa.text("coalesce('published_at', 'collected_at')")], unique=False)
    op.create_index('ix_raw_source_pub', 'raw_content', ['source_id', 'published_at'], unique=False)
    op.create_index('ux_raw_source_external', 'raw_content', ['source_id', 'external_id'], unique=True, postgresql_where='external_id IS NOT NULL')
    op.create_table('processed_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_content_id', sa.UUID(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('language_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('language_uncertain', sa.Boolean(), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language_code IS NULL OR language_code ~ '^[a-z]{2,5}$'", name='ck_pc_language'),
    sa.CheckConstraint("status IN ('pending_analysis','analyzed','scoring_failed','clean_degraded')", name='ck_pc_status'),
    sa.CheckConstraint('language_confidence IS NULL OR language_confidence BETWEEN 0 AND 1', name='ck_pc_lang_conf'),
    sa.ForeignKeyConstraint(['raw_content_id'], ['raw_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_content_id')
    )
    op.create_index('ix_pc_cluster', 'processed_content', ['cluster_id'], unique=False)
    op.create_index('ix_pc_lang', 'processed_content', ['language_code', 'processed_at'], unique=False)
    op.create_index('ix_pc_pending', 'processed_content', ['processed_at'], unique=False, postgresql_where="status = 'pending_analysis'")
    op.create_index('ix_pc_simhash', 'processed_content', ['simhash'], unique=False, postgresql_where='simhash IS NOT NULL')
    op.create_table('nlp_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processed_content_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('sentiment_label', sa.Text(), nullable=False),
    sa.Column('sentiment_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sentiment_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hostility_label', sa.Text(), nullable=False),
    sa.Column('hostility_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('hostility_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disinfo_label', sa.Text(), nullable=False),
    sa.Column('disinfo_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('disinfo_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stance_label', sa.Text(), nullable=False),
    sa.Column('stance_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('stance_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inference_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disinfo_label IN ('likely_reliable','uncertain','likely_unreliable','not_applicable')", name='ck_nlp_disinfo'),
    sa.CheckConstraint("hostility_label IN ('none','hostile_rhetoric','threatening_language','not_applicable')", name='ck_nlp_hostility'),
    sa.CheckConstraint("sentiment_label IN ('negative','neutral','positive','not_applicable')", name='ck_nlp_sentiment'),
    sa.CheckConstraint("stance_label IN ('supportive','neutral','opposed','not_applicable')", name='ck_nlp_stance'),
    sa.CheckConstraint('sentiment_confidence BETWEEN 0 AND 1 AND hostility_confidence BETWEEN 0 AND 1 AND disinfo_confidence BETWEEN 0 AND 1 AND stance_confidence BETWEEN 0 AND 1', name='ck_nlp_confidences'),
    sa.ForeignKeyConstraint(['processed_content_id'], ['processed_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processed_content_id', 'model_version', name='ux_nlp_content_model')
    )
    op.create_index('ix_nlp_content', 'nlp_results', ['processed_content_id'], unique=False)
    op.create_index('ix_nlp_entities', 'nlp_results', ['entities'], unique=False, postgresql_using='gin')
    op.create_index('ix_nlp_hostility', 'nlp_results', ['hostility_label', 'created_at'], unique=False, postgresql_where="hostility_label <> 'none'")
    op.create_index('ix_nlp_topics', 'nlp_results', ['topics'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nlp_topics', table_name='nlp_results', postgresql_using='gin')
    op.drop_index('ix_nlp_hostility', table_name='nlp_results', postgresql_where="hostility_label <> 'none'")
    op.drop_index('ix_nlp_entities', table_name='nlp_results', postgresql_using='gin')
    op.drop_index('ix_nlp_content', table_name='nlp_results')
    op.drop_table('nlp_results')
    op.drop_index('ix_pc_simhash', table_name='processed_content', postgresql_where='simhash IS NOT NULL')
    op.drop_index('ix_pc_pending', table_name='processed_content', postgresql_where="status = 'pending_analysis'")
    op.drop_index('ix_pc_lang', table_name='processed_content')
    op.drop_index('ix_pc_cluster', table_name='processed_content')
    op.drop_table('processed_content')
    op.drop_index('ux_raw_source_external', table_name='raw_content', postgresql_where='external_id IS NOT NULL')
    op.drop_index('ix_raw_source_pub', table_name='raw_content')
    op.drop_index('ix_raw_effective_time', table_name='raw_content')
    op.drop_table('raw_content')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index('ix_audit_denied', table_name='audit_logs', postgresql_where="result = 'denied'")
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ux_alert_open', table_name='alerts', postgresql_where="status IN ('new','acknowledged','under_review')")
    op.drop_index('ix_alerts_queue', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_index('ix_sources_due', table_name='sources', postgresql_where="status = 'enabled'")
    op.drop_table('sources')
    op.drop_index('ix_scores_trend', table_name='indicator_scores')
    op.drop_index('ix_scores_pending_alert', table_name='indicator_scores', postgresql_where="computed AND NOT alert_evaluated AND severity IN ('low','medium','high','critical')")
    op.drop_table('indicator_scores')
    # ### end Alembic commands ###
